// Array of photo challenge tasks
const tasks = [
"A steaming cup of coffee/tea",
"A cozy reading nook",
"Sunlight streaming through a window",
"Shadows cast by blinds",
"A handwritten note or letter",
"A well-worn book with a bookmark",
"A clock showing an interesting time",
"A vintage key or keychain",
"A reflection in a spoon",
"A messy artist's workspace",
"A single raindrop on a leaf",
"Morning dew on grass",
"A tiny flower growing through concrete",
"A close-up of tree bark texture",
"A snail on a rainy sidewalk",
"The pattern of ripples in water",
"A pile of autumn leaves",
"A feather lying on the ground",
"A spider web catching the sunlight",
"A row of ants carrying food",
"A black-and-white silhouette",
"A close-up of cracked paint on a wall",
"A reflection in a puddle",
"A blurred cityscape at night",
"Light trails from moving cars",
"A distorted image through glass or water",
"An extreme close-up of fabric texture",
"Colorful shadows cast by an object",
"A double exposure effect",
"The grain of an old wooden table",
"Hands holding a tiny object",
"A close-up of an eye with a reflection",
"A person tying their shoelaces",
"A smile with only lips visible",
"Wind blowing through someones hair",
"A silhouette against a sunset",
"Someone peeking from behind an object",
"A hand reaching toward the camera",
"Fingers playing a musical instrument",
"A reflection of a face in sunglasses",
"A pair of mismatched socks",
"A broken pencil tip",
"A melted candle",
"A tangled mess of earbuds",
"A close-up of a zipper",
"The inside of a wristwatch",
"A stack of colorful sticky notes",
"A toy car on a real street",
"A fork casting a long shadow",
"A neon sign glowing in the dark",
"A single streetlight at night",
"A close-up of graffiti textures",
"A bike leaning against a wall",
"A blurred passerby in motion",
"A pigeon on a city sidewalk",
"A bus stop with people waiting",
"A fire escape from an interesting angle",
"Neon lights reflecting in a puddle",
"A bridge disappearing into fog",
"A discarded ticket stub on the ground",
"A single cherry on a plate",
"A dripping ice cream cone",
"Bubbles in a soda glass",
"A broken chocolate bar",
"Coffee foam in a latte",
"A slice of cake with crumbs",
"A spoon sinking into honey",
"A row of colorful macarons",
"A piece of bread torn in half",
"A lemon slice in water",
"The inside of a guitar soundhole",
"Piano keys with dramatic lighting",
"A violin bow on strings",
"A turntable spinning a vinyl record",
"A singers microphone up close",
"Drumsticks resting on a drum",
"A close-up of a trumpets valves",
"A music sheet with handwritten notes",
"The wear on a guitarists fretboard",
"Headphones with an unplugged cable",
"A train track disappearing into the distance",
"A rearview mirror reflection",
"A plane wing above the clouds",
"A road sign in an empty highway",
"A bicycle tire with a shadow",
"A hand holding a train ticket",
"A gas station at night",
"Suitcases stacked together",
"A boat tied to a dock",
"A footprint on a sandy beach",
"Light passing through a prism",
"Candlelight flickering on a wall",
"A streetlamp casting a geometric shadow",
"A backlit leaf glowing",
"A sunrise reflected in a window",
"Light shining through a lace curtain",
"A hand reaching toward a beam of light",
"Shadows forming an interesting pattern",
"The glow of a phone screen in the dark",
"A small lantern illuminating a dark space",
];

// Function to get a random task from the tasks array and display it
function getTask() {
    const randomTask = tasks[Math.floor(Math.random() * tasks.length)]; // Selects a random task
    document.getElementById("task").textContent = randomTask; // Displays the random task in the element with id "task"
    document.getElementById("completed").style.display = "none"; // Hides the "completed" message
}

// Variable to keep track of the number of completed challenges
let count = 0;

// Function to mark a task as completed
function markCompleted() {
    count++; // Increments the count of completed tasks
    document.getElementById("count").innerText = count; // Updates the count display
    document.getElementById("completed").style.display = "block"; // Shows the "completed" message
    document.querySelector("textarea").value = ""; // Clears the textarea
}